apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-gloo-ingress
  annotations:
    kubernetes.io/ingress.class: "gloo"
spec:
  rules:
    - http:
      paths:
        - path: /gloo
          pathType: Prefix
          backend:
            serviceName: project-gloo-service
            servicePort: 3000
