apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: project-ingress
  annotations:
    kubernetes.io/ingress.class: gloo
spec:
  rules:
    http:
      paths:
        - path: /.*
          backend:
            serviceName: project-service
            servicePort: 3000
