apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /foo
            pathType: Prefix
            backend:
              serviceName: project-gloo-service
              servicePort: 3000
