apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
      http:
        paths:
          - path: /nginx
            backend:
              serviceName: project-nginx-service
              servicePort: 3000
