apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: project-nginx-ingress
  namespace: project
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: project-nginx-service
          servicePort: 3000